source "https://rubygems.org"

#=================================[=]
gem "jekyll", "~> 4.3.4"
gem "jekyll-seo-tag"
gem "webrick"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-sitemap"
  gem "jekyll-assets"
end

#=================================[=]
gem "kramdown"
gem "dotenv"

#=================================[=]
gem "bundler", "~> 2.0"
gem "html-proofer"
gem 'rouge'