source "https://rubygems.org"

#=================================[=] Menggunakan Jekyll
gem "jekyll", "~> 4.3.4"
gem "jekyll-seo-tag"
gem "webrick"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-sitemap"
#gem "jekyll-paginate"
  gem "jekyll-toc"
end

#=================================[=] Tambahkan gem lain sesuai kebutuhan
gem "kramdown"
gem "dotenv"
gem 'jekyll-tidy'
#=================================[=] Pastikan untuk menginstal bundler jika belum
gem "bundler", "~> 2.0" 
#gem "sassc-rails"
#gem "sassc"
gem "html-proofer"
