# ============[]
title: "Testing On"
description: "Tempat Berbagi Keluh Kesah"
lang: "id"
keywoard: ""
timezone: Asia/Jakarta
author: "Putra Jaya"
data-theme: 'dark' # dark/light
# ============[]
url: ""
baseurl: ""
# ============[]
collections:
  projects:
    output: true
  pages:
    output: true
# ============[]
facebook: ""
twitter: ""
instagram: ""
youtube: ""
linkedin: ""
github: ""
discord: ""
# ============[]
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/:title/"
      toc: true
# ============[]
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - drafts
  - .sass-cache/
  - .jekyll-cache/
# ============[]
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-sitemap
  - jekyll-tidy
  - jekyll-toc
highlighter: rouge
markdown: kramdown