source "https://rubygems.org"

#=================================[=] Menggunakan Jekyll
gem "jekyll", "~> 4.3.4"
gem "jekyll-seo-tag"
gem "webrick"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-sitemap"
end

#=================================[=] Tambahkan gem lain sesuai kebutuhan
gem "kramdown"
gem "dotenv"
#=================================[=] Pastikan untuk menginstal bundler jika belum
gem "bundler", "~> 2.0" 
gem "html-proofer"